version: '3.7'

services:
  db:
    image: mongo:4.4.1
    container_name: travel-itinerary-db
    volumes:
      - ./docker/mongodb-data:/data
    command: --serviceExecutor adaptive
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: travel-itinerary
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: travel-itinerary-db-admin
    restart: unless-stopped
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081
    depends_on:
      - db

  api:
    image: api
    container_name: api
    stdin_open: true
    build:
      context: api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - /home/node/app/node_modules
      - ./api:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./api/.env
    ports:
      - '5000:5000'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-web-server
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/key.pem:/root/ssl/key.pem
      - ./nginx/cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
      - "80:80"
    # depends_on:
    #   - api
