# Permissions added for node user because of this: https://github.com/BretFisher/node-docker-good-defaults
FROM node:lts-slim@sha256:c785e617c8d7015190c0d41af52cc69be8a16e3d9eb7cb21f0bb58bcfca14d6b

RUN apk add dumb-init procps

# ENV NODE_ENV=development

# Latest npm regardless of node version.
RUN npm install --location=global @nestjs/cli

# USER node

WORKDIR /home/node/app

RUN ls

# COPY --chown=node:node ./package*.json ./
COPY ./package*.json ./

ENV PATH /home/node/app/node_modules/.bin:$PATH

RUN ls

RUN npm install

COPY src ./src

CMD [ "dumb-init" , "npm", "run", "start:dev" ]

RUN echo '🐳 Docker build success'
